# Generated by Django 3.1.1 on 2020-09-19 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название категории')),
                ('order', models.IntegerField(blank=True, default=1, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idu', models.IntegerField(unique=True, verbose_name='Идентификатор')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Фамилия')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Ник')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефонный номер')),
                ('photo', models.ImageField(default='kafehan/clients/photo/no_photo.png', upload_to='kafehan/clients/photo/%Y/%m/%d', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефонный номер')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментарий')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('dateOrder', models.DateTimeField(blank=True, null=True, verbose_name='Дата заказа')),
                ('dateAccess', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('dateDone', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('dateCanceled', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
                ('cost', models.IntegerField(default=0, verbose_name='Сумма')),
                ('payed', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('canceled', models.IntegerField(null=True, verbose_name='Отменён')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kafehan.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderPayType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Способ')),
                ('slag', models.CharField(max_length=255, verbose_name='slag')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Статус')),
                ('slag', models.CharField(max_length=255, unique=True, verbose_name='slag')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Способ')),
                ('slag', models.CharField(max_length=255, unique=True, verbose_name='slag')),
            ],
            options={
                'verbose_name': 'Способ получения',
                'verbose_name_plural': 'Способы получения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='Номер стола')),
                ('photo', models.ImageField(null=True, upload_to='kafehan/product/photo/%Y/%m/%d', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('weight', models.CharField(blank=True, max_length=255, verbose_name='Вес')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
                ('visible', models.BooleanField(default=True, verbose_name='Отображать')),
                ('photo', models.ImageField(blank=True, default='', upload_to='kafehan/product/photo/%Y/%m/%d', verbose_name='Фото')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kafehan.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kafehan.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kafehan.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продукт в заказе',
                'verbose_name_plural': 'Продукты в заказе',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='pay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kafehan.orderpaytype', verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kafehan.orderstatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kafehan.table', verbose_name='Стол'),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kafehan.ordertype', verbose_name='Способ получения'),
        ),
        migrations.CreateModel(
            name='AdminKafeHan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kafehan.client', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Админ кафе',
                'verbose_name_plural': 'Админ кафе',
            },
        ),
    ]
