# Generated by Django 3.1.1 on 2020-09-20 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kafehan', '0003_auto_20200919_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlinepay',
            options={'verbose_name': 'Онлайн платёж', 'verbose_name_plural': 'Онлайн платежи'},
        ),
    ]
