# Generated by Django 3.1.1 on 2020-09-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafehan', '0004_auto_20200920_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinepay',
            name='id_pay',
            field=models.CharField(max_length=255, unique=True, verbose_name='Идентификатор платежа'),
        ),
    ]
